services:
  apptest:
    build:
      context: .
      dockerfile: tests/Dockerfile
  app:
    build:
      context: .
      target: runtime
    ports:
      - 8080:8080
    depends_on:
      apptest:
        condition: service_completed_successfully
  alterapp:
    build:
      context: .
      target: alternative_build
    ports:
      - 8081:8080
    depends_on:
      apptest:
        condition: service_completed_successfully